### ISSUE TITLE
Issue with directories and linters

### ISSUE THREAD

**Issue by MarcoDDM** [J-C-S-V/awesome-books-app#2]
Hi Juank! Great job so far! ✈ We saw that you were doing a great effort on this project. We think that your project could be better if you make a few changes in the future.

- We noticed that you add the Linters set up at last. Is going to be better if you add that at first the next time. 
- Nice work, your code is looking awesome, maybe it would be good to follow the gitignore configuration steps to avoid overlapses in your commits and keep the versions of your code clearer

**Comment by J-C-S-V** [comment]
Thank you for the feedback!!!!!
